### ISSUE TITLE
Claims.pkl file is missing

### ISSUE THREAD

**Issue by ihammad90** [mitchelldehaven/bevers#1]
While running this repo for fever.sh i encountered issue which says claims.pkl file is missing.

**Comment by mitchelldehaven** [comment]
Okay, probably this weekend I'll take a look. I thought I did a full run through from a new repo when I did my testing, but apparently I missed some steps.

**Comment by ihammad90** [comment]
Did you do it?

**Comment by mitchelldehaven** [comment]
Yes, sorry about the delay, I ended up being out of town for about a week. Similar to the other issue you ran into, this is likely due to a previous command failing and thus resulting in missing files, leading to future commands failing. Since `set -euo pipefail` wasn't in the bash script, it continues to run commands even if previous ones are failing, so I added that to `run_fever.sh`. You will want to pull the most recent commits, as I also noticed that I had `bevers_v2` as the conda environment, rather than `bevers`, which is the conda environment created when `setup.sh` is ran.
